-- =========================================================
-- TrackMenu - Esquema de Base de Datos para Supabase
-- Copiá y pegá este script en el SQL Editor de tu panel Supabase
-- =========================================================

-- 1. Tabla de Productos
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL,
  category TEXT DEFAULT 'Hamburguesas',
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Mesas
CREATE TABLE IF NOT EXISTS public.tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number INT UNIQUE NOT NULL,
  status TEXT DEFAULT 'libre' CHECK (status IN ('libre', 'ocupada')),
  current_order JSONB DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla de Pedidos / Comandas
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_number INT NOT NULL,
  status TEXT DEFAULT 'en_preparacion' CHECK (status IN ('en_preparacion', 'listo', 'entregado', 'cancelado')),
  time TEXT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  total NUMERIC(10, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================
-- Datos Iniciales de Prueba (Seed Data)
-- =========================================================

-- Insertar Productos
INSERT INTO public.products (name, description, price, category, image)
VALUES
  ('Burger clásica', 'Doble smash, cheddar, cebolla caramelizada y salsa de la casa.', 1890, 'Hamburguesas', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-qw3nfbnetm1rXMnXgRGCZbDkTOypHG.png'),
  ('Papas a la piedra', 'Crocantes por fuera, suaves por dentro, con romero y sal de escamas.', 950, 'Hamburguesas', 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=500&q=80'),
  ('Milanesa de pollo', 'Rebozada crocante con limón y ensalada fresca.', 1050, 'Hamburguesas', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-qw3nfbnetm1rXMnXgRGCZbDkTOypHG.png'),
  ('Limonada casera', 'Limón natural, menta y un toque de jengibre.', 780, 'Bebidas', 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=500&q=80'),
  ('Cheesecake de frutos rojos', 'Cremoso, suave y con salsa de frutos rojos.', 1200, 'Postres', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=500&q=80')
ON CONFLICT DO NOTHING;

-- Insertar 12 Mesas (Mesas 4 y 7 ocupadas por defecto)
INSERT INTO public.tables (number, status, current_order)
VALUES
  (1, 'libre', NULL),
  (2, 'libre', NULL),
  (3, 'libre', NULL),
  (4, 'ocupada', '{"id": 104, "time": "20:14", "items": [{"name": "Burger clásica", "quantity": 1, "price": 1890}, {"name": "Papas a la piedra", "quantity": 1, "price": 950}], "total": 2840}'),
  (5, 'libre', NULL),
  (6, 'libre', NULL),
  (7, 'ocupada', '{"id": 107, "time": "20:30", "items": [{"name": "Milanesa de pollo", "quantity": 1, "price": 1050}], "total": 1050}'),
  (8, 'libre', NULL),
  (9, 'libre', NULL),
  (10, 'libre', NULL),
  (11, 'libre', NULL),
  (12, 'libre', NULL)
ON CONFLICT (number) DO NOTHING;

-- Habilitar Políticas RLS básicas para acceso público/autenticado
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Lectura pública de productos" ON public.products FOR SELECT USING (true);
CREATE POLICY "Lectura pública de mesas" ON public.tables FOR SELECT USING (true);
CREATE POLICY "Actualización pública de mesas" ON public.tables FOR UPDATE USING (true);
CREATE POLICY "Lectura pública de pedidos" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Inserción pública de pedidos" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Actualización pública de pedidos" ON public.orders FOR UPDATE USING (true);
