-- Migration: 001_create_products_table.sql
-- Descripción: Crea la tabla de productos del menú

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL,
  category TEXT DEFAULT 'Hamburguesas',
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comentarios de tabla y columnas
COMMENT ON TABLE public.products IS 'Catálogo de comidas, bebidas y postres';
COMMENT ON COLUMN public.products.category IS 'Categoría del producto (Hamburguesas, Bebidas, Postres, etc.)';
