-- Migration: 002_create_tables_table.sql
-- Descripción: Crea la tabla de mesas del salón

CREATE TABLE IF NOT EXISTS public.tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number INT UNIQUE NOT NULL,
  status TEXT DEFAULT 'libre' CHECK (status IN ('libre', 'ocupada')),
  current_order JSONB DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comentarios
COMMENT ON TABLE public.tables IS 'Estado y asignación de mesas del restaurante';
COMMENT ON COLUMN public.tables.status IS 'Estado de la mesa: libre u ocupada';
