-- Migration: 003_create_orders_table.sql
-- Descripción: Crea la tabla de pedidos y comandas

CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_number INT NOT NULL,
  status TEXT DEFAULT 'en_preparacion' CHECK (status IN ('en_preparacion', 'listo', 'entregado', 'cancelado')),
  time TEXT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  total NUMERIC(10, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices de consulta rápida
CREATE INDEX IF NOT EXISTS idx_orders_table_number ON public.orders(table_number);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);

-- Comentarios
COMMENT ON TABLE public.orders IS 'Historial y pedidos en curso enviados a cocina';
